"""
modules/store — local SQLite source of truth (replaces Notion).

Public surface:
    from modules.store import Store
    store = Store()
    store.create_all()        # idempotent schema creation
"""
from __future__ import annotations

from .db import get_engine, init_db, make_engine, new_session
from .models import (
    AiSuggestion,
    AnalysisJob,
    AnalysisType,
    ArtifactKind,
    Collection,
    Concept,
    ConceptState,
    Edge,
    EdgeChannel,
    EdgeStatus,
    JobStatus,
    MathObject,
    MathObjectProject,
    MathObjectRelevance,
    MathObjectType,
    Paper,
    PaperArtifact,
    PaperChunk,
    PaperCollection,
    PaperProject,
    PaperRole,
    PaperSource,
    PaperStatus,
    PaperTag,
    ParseBackend,
    ParseJob,
    ParseScope,
    Project,
    ProjectConcept,
    RegionLabel,
    RelationType,
    ScopeKind,
    ScopePurpose,
    SuggestionStatus,
    SuggestionType,
    Tag,
    VerificationStatus,
)
from .repository import Store, normalize_title

__all__ = [
    "Store",
    "normalize_title",
    "get_engine",
    "make_engine",
    "init_db",
    "new_session",
    "Paper",
    "Concept",
    "Edge",
    "Project",
    "ProjectConcept",
    "PaperStatus",
    "PaperSource",
    "ConceptState",
    "VerificationStatus",
    "RelationType",
    "EdgeChannel",
    "EdgeStatus",
    # Phase 1 — organization, selective parse/analysis, AI quarantine
    "Tag",
    "Collection",
    "PaperTag",
    "PaperCollection",
    "PaperProject",
    "PaperRole",
    "ParseScope",
    "ParseJob",
    "PaperArtifact",
    "PaperChunk",
    "AnalysisJob",
    "AiSuggestion",
    "MathObject",
    "MathObjectProject",
    "ScopeKind",
    "ScopePurpose",
    "JobStatus",
    "ParseBackend",
    "AnalysisType",
    "SuggestionType",
    "SuggestionStatus",
    "RegionLabel",
    "ArtifactKind",
    "MathObjectType",
    "MathObjectRelevance",
]
