"""
graph-server/main.py
────────────────────
Lightweight FastAPI application that serves the dependency graph HTML file
generated by the Dependency Grapher module.

The HTML file is written to the shared `graph_static` Docker volume by the
orchestrator and served from here at:

    GET /         → redirects to /graph
    GET /graph    → the interactive PyVis dependency graph (HTML)
    GET /health   → health-check endpoint (returns {"status": "ok"})
"""

from __future__ import annotations

from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, HTMLResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles

STATIC_DIR = Path("/app/static")
GRAPH_FILE = STATIC_DIR / "graph.html"

app = FastAPI(
    title="Paper Pipeline — Dependency Graph Server",
    description="Serves the auto-generated paper dependency graph.",
    version="1.0.0",
)

# Serve any other static assets (CSS, JS injected by PyVis) from /static
if STATIC_DIR.exists():
    app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")


@app.get("/", include_in_schema=False)
async def root() -> RedirectResponse:
    return RedirectResponse(url="/graph")


@app.get("/health")
async def health() -> dict:
    """Health check — returns 200 OK when the service is running."""
    return {"status": "ok"}


@app.get("/graph", response_class=HTMLResponse)
async def serve_graph() -> FileResponse:
    """
    Serve the latest dependency graph HTML generated by the Dependency Grapher.

    Returns 503 if the graph has not been generated yet (first run may take up
    to 12 hours).
    """
    if not GRAPH_FILE.exists():
        raise HTTPException(
            status_code=503,
            detail=(
                "Graph not yet generated. "
                "The orchestrator generates it every 12 hours — please check back later."
            ),
        )
    return FileResponse(str(GRAPH_FILE), media_type="text/html")
