"""
graph-server/main.py
────────────────────
Lightweight FastAPI application that serves the dependency graph HTML files
generated by the Dependency Grapher module.

The HTML files are written to the shared `graph_static` Docker volume by the
orchestrator and served from here at:

    GET /                    → redirects to /index
    GET /index               → landing page with links to both graph views
    GET /graph/verified      → verified SB concepts + Edges DB relations
    GET /graph/inbox         → KI inbox concepts + AI-proposed edges
    GET /health              → health-check endpoint (returns {"status": "ok"})
    GET /status              → reports which graph files exist and their mtime
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles

STATIC_DIR        = Path(os.environ.get("GRAPH_STATIC_DIR", "/app/static"))
GRAPH_VERIFIED    = STATIC_DIR / "graph_verified.html"
GRAPH_INBOX       = STATIC_DIR / "graph_inbox.html"
INDEX_FILE        = STATIC_DIR / "index.html"

app = FastAPI(
    title="Paper Pipeline — Knowledge Graph Server",
    description=(
        "Serves the auto-generated concept dependency graphs produced by "
        "the Dependency Grapher module (Module 5).\n\n"
        "Two views are available:\n"
        "- **/graph/verified** — promoted Second Brain concepts with human-verified edges\n"
        "- **/graph/inbox**    — Knowledge Inbox concepts with AI-proposed edges"
    ),
    version="2.0.0",
)

# ── Static file mount ─────────────────────────────────────────────────────────
# Serves PyVis-injected JS/CSS assets and all graph HTML files.
# Mount after app creation so the route declarations below take priority.
if STATIC_DIR.exists():
    app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")


# ── Redirects ─────────────────────────────────────────────────────────────────

@app.get("/", include_in_schema=False)
async def root() -> RedirectResponse:
    return RedirectResponse(url="/index")


# ── Health + status ───────────────────────────────────────────────────────────

@app.get("/health", tags=["ops"])
async def health() -> dict:
    """Health check — returns 200 OK when the service is running."""
    return {"status": "ok"}


@app.get("/status", tags=["ops"])
async def status() -> JSONResponse:
    """
    Report which graph files exist and when they were last generated.
    Useful for monitoring whether the orchestrator is running correctly.
    """
    def _file_info(path: Path) -> dict:
        if not path.exists():
            return {"exists": False, "last_generated": None}
        mtime = path.stat().st_mtime
        return {
            "exists": True,
            "last_generated": datetime.fromtimestamp(
                mtime, tz=timezone.utc
            ).isoformat(),
            "size_bytes": path.stat().st_size,
        }

    return JSONResponse({
        "graph_verified": _file_info(GRAPH_VERIFIED),
        "graph_inbox":    _file_info(GRAPH_INBOX),
        "index":          _file_info(INDEX_FILE),
    })


# ── Graph views ───────────────────────────────────────────────────────────────

@app.get("/index", response_class=HTMLResponse, tags=["graph"])
async def serve_index() -> FileResponse:
    """
    Landing page with links to both graph views and the edge-type colour legend.
    Generated by DependencyGrapher alongside the graph files.
    """
    _require_file(
        INDEX_FILE,
        "Index page not yet generated. The orchestrator generates it every "
        "12 hours — please check back later.",
    )
    return FileResponse(str(INDEX_FILE), media_type="text/html")


@app.get("/graph/verified", response_class=HTMLResponse, tags=["graph"])
async def serve_verified() -> FileResponse:
    """
    Interactive graph of verified Second Brain concepts and human-confirmed
    edges from the Edges DB.

    Node shapes:
      - Rectangle = Paper
      - Ellipse   = Concept (colour by type)

    Edge colours:
      - Red    = depends_on
      - Green  = enables
      - Blue   = generalizes
      - Purple = special_case_of
      - Grey   = related
      - White dashed = source (paper → concept)
    """
    _require_file(
        GRAPH_VERIFIED,
        "Verified concept graph not yet generated. "
        "The orchestrator generates it every 12 hours — please check back later.",
    )
    return FileResponse(str(GRAPH_VERIFIED), media_type="text/html")


@app.get("/graph/inbox", response_class=HTMLResponse, tags=["graph"])
async def serve_inbox() -> FileResponse:
    """
    Interactive graph of Knowledge Inbox concepts (unverified) with
    AI-proposed edges parsed from Edge Suggestions JSON.

    Dashed edges = AI-proposed (not human-verified).
    Node colour encodes verification_status:
      - Green  = verified
      - Orange = unverified
      - Red    = rejected
    """
    _require_file(
        GRAPH_INBOX,
        "Inbox concept graph not yet generated. "
        "The orchestrator generates it every 12 hours — please check back later.",
    )
    return FileResponse(str(GRAPH_INBOX), media_type="text/html")


# ── Legacy redirect ───────────────────────────────────────────────────────────

@app.get("/graph", include_in_schema=False)
async def legacy_graph() -> RedirectResponse:
    """Redirect old /graph endpoint to the new verified view."""
    return RedirectResponse(url="/graph/verified")


# ── Helper ────────────────────────────────────────────────────────────────────

def _require_file(path: Path, detail: str) -> None:
    """Raise HTTP 503 if the given file does not exist yet."""
    if not path.exists():
        raise HTTPException(status_code=503, detail=detail)