# modules/ingestion/prompts.py — re-export from staging location
from ..ingestion_prompts import (
    EDGE_CONFIRMATION_SYSTEM_PROMPT,
    EXTRACTION_SYSTEM_PROMPT,
    LATEX_FORMATTING_RULES,
    LINKING_SYSTEM_PROMPT_V1,
    LINKING_SYSTEM_PROMPT_V2,
    REEXTRACT_SYSTEM_PROMPT,
    SKELETON_SYSTEM_PROMPT,
)

__all__ = [
    "LATEX_FORMATTING_RULES",
    "EXTRACTION_SYSTEM_PROMPT",
    "SKELETON_SYSTEM_PROMPT",
    "LINKING_SYSTEM_PROMPT_V1",
    "LINKING_SYSTEM_PROMPT_V2",
    "EDGE_CONFIRMATION_SYSTEM_PROMPT",
    "REEXTRACT_SYSTEM_PROMPT",
]
